spring:
  application:
    name: habit_tracker_back

  datasource:
    url: jdbc:postgresql://localhost:5432/habit_tracker_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    jwt:
      token:
        secret: your_jwt_secret_key
        expiration: 3600000 # 1 hour in milliseconds
