name: Back-end Feature
description: Template para desenvolvimento de novas features no back-end
title: "[feature][backend] "
labels: ["backend", "feature", "to do"]
body:
  - type: input
    id: feature_name
    attributes:
      label: 🧩 Nome da Feature
      description: Nome resumido da funcionalidade.
      placeholder: "Ex: CRUD de hábitos"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📃 Descrição da Feature
      description: Explique o que essa feature faz, como funciona e para que serve.
      placeholder: "Ex: Criar os endpoints necessários para gerenciar hábitos (listar, criar, editar, deletar)"
    validations:
      required: true

  - type: textarea
    id: endpoints
    attributes:
      label: 🌐 Endpoints esperados
      description: Liste os endpoints REST que essa feature criará ou alterará.
      placeholder: |
        - [ ] GET /habits
        - [ ] POST /habits
        - [ ] PUT /habits/{id}
        - [ ] DELETE /habits/{id}
    validations:
      required: false

  - type: textarea
    id: tasks
    attributes:
      label: ✅ Subtarefas / Checklist técnico
      description: Liste as subtarefas técnicas que precisam ser realizadas para concluir esta feature.
      placeholder: |
        - [ ] Criar classe de entidade
        - [ ] Criar repositório JPA
        - [ ] Criar DTOs de entrada e saída
        - [ ] Implementar camada de serviço
        - [ ] Criar controller com os endpoints
        - [ ] Validar dados com annotations (ex: @NotBlank)
        - [ ] Criar testes unitários
        - [ ] Criar testes de integração
        - [ ] Documentar endpoints no Swagger ou README
    validations:
      required: false

  
  - type: textarea
    id: tests
    attributes:
      label: 🧪 Casos de Teste Esperados
      description: Quais testes você pretende cobrir para essa feature?
      placeholder: |
        - [ ] Criar hábito com dados válidos → 201 Created
        - [ ] Criar hábito com dados faltando → 400 Bad Request
        - [ ] Listar hábitos sem login → 403 Forbidden
        - [ ] Editar hábito de outro usuário → 403 Forbidden
    validations:
      required: false

  - type: input
    id: estimate
    attributes:
      label: ⏱️ Tempo estimado
      placeholder: "Ex: 2h"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: 🗒️ Notas ou observações
      description: Algum detalhe importante, exceção ou observação especial?
      placeholder: "Ex: A rota será privada, precisa de autenticação JWT"
    validations:
      required: false
